#Turn on living room lights & den corner in late pm
- alias: 'LR lights on late pm'
  trigger:
    platform: sun
    event: sunset
    offset: "-02:30:00"
  action:
    service: light.turn_on
    entity_id:
      - light.living_room_c_table
      - light.living_room_corner
      - light.den_corner
     
#Turn on basement corner light in late pm
- alias: 'basement corner light in late pm'
  trigger:
    platform: time
    after: '15:00:00'
  action:
    service: light.turn_on
    entity_id:
      - light.basement

#Turn on basement stairs light in late pm
- alias: 'turn on basement stairs light in late pm'
  trigger:
    platform: sun
    event: sunset
    offset: "-02:00:00"
  action:
    service: switch.turn_on
    entity_id: switch.basement_stairs_switch_3_0

#Turn on master bedroom lights in late pm
- alias: 'master bedroom lights in late pm'
  trigger:
    platform: sun 
    event: sunset
    offset: "-01:00:00"
  action:
    service: light.turn_on
    entity_id:
      - light.master
      - light.master_corner

#Turn on master bedroom nightstand lights in late pm
- alias: 'master bedroom nightstand lights in late pm'
  trigger:
    platform: time
    after: '19:30:00'
  action:
    service: light.turn_on
    entity_id:
      - light.master_left_night_stand
      - light.master_right_night_stand

#Turn on den light in morning during the week
- alias: 'den light in morning during the week'
  trigger:
    platform: time
    after: '07:00:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    service: light.turn_on
    entity_id:
      - light.den
      - light.den_window
      - light.desk_drawer_level_14_0
      - light.tiffany_level_12_0

#Turn off den lights during the week
- alias: 'den lights off at 10pm during the week'
  trigger:
    platform: time
    after: '22:00:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    service: light.turn_off
    entity_id:
      - light.den
      - light.den_window
      - light.desk_drawer_level_14_0
      - light.tiffany_level_12_0

#Turn off lights at midnight
- alias: 'lights off at midnight'
  trigger:
    platform: time
    after: '23:59:00'
  action:
    service: light.turn_off
    entity_id:
      - light.master
      - light.master_corner
      - light.living_room_c_table
      - light.living_room_corner
      - light.den_corner

#Turn off master nightstand lights at 12:30am
- alias: 'master nightstand lights off at 12:30am'
  trigger:
    platform: time
    after: '00:30:00'
  action:
    service: light.turn_off
    entity_id:
      - light.master_left_night_stand
      - light.master_right_night_stand

#Turn off basement corner light at 12:45am 
- alias: 'basement corner light off at 12:45am'
  trigger:
    platform: time
    after: '00:45:00'
  action:
    service: light.turn_off
    entity_id:
      - light.basement

#Turn off basement lights in late pm
- alias: 'turn off basement lights in late pm'
  trigger:
    platform: time 
    after: "00:00:00"
  action:
    service: homeassistant.turn_off
    entity_id: 
      - switch.basement_stairs_switch_3_0
      - light.basement_3way_dimmer_level_25_0
      - light.basement_wall
      - light.basement_cabinet

#Turn off any lights in early morning
- alias: 'entry light off in early am'
  trigger:
    platform: time
    after: '02:30:00'
  action:
    service: homeassistant.turn_off
    entity_id:
      - light.entry_hall
      - light.office
      - light.lightstrip
      - switch.kitchen_switch_4_0
      - light.living_room

#Turn on living room camera switch based on battery levels
- alias: 'lr camera switch on'
  trigger:
    platform: template
    value_template: "{% if states.device_tracker.jay_note_4.attributes.battery | float <= 50.0 %}true{% endif %}"
  action:
    service: switch.turn_on
    entity_id: switch.living_room_camera_power

#Turn off living room camera switch based on battery levels
- alias: 'lr camera switch off'
  trigger:
    platform: template
    value_template: "{% if states.device_tracker.jay_note_4.attributes.battery | float >= 95.0 %}true{% endif %}"
  action:
    service: switch.turn_off
    entity_id: switch.living_room_camera_power

#Turn on master bedroom phone power switch based on battery levels
- alias: 'master phone pwr switch on'
  trigger:
    platform: template
    value_template: "{% if states.device_tracker.jayn5_nexus_5x.attributes.battery | float <= 65.0 %}true{% endif %}"
  action:
    service: switch.turn_on
    entity_id: switch.bedroom_phone_power

#Turn off master bedroom phone power switch based on battery levels
- alias: 'master phone pwr switch off'
  trigger:
    platform: template
    value_template: "{% if states.device_tracker.jayn5_nexus_5x.attributes.battery | float >= 80.0 %}true{% endif %}"
  action:
    service: switch.turn_off
    entity_id: switch.bedroom_phone_power

#when basement nuc player pauses
- alias: "Media player paused/stopped"
  trigger:
    platform: state
    entity_id: media_player.nuci5
    from: 'playing'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    service: scene.turn_on
    entity_id: scene.basement_normal

#when basement nuc player starts playing
- alias: "Media player paused/stopped"
  trigger:
    platform: state
    entity_id: media_player.nuci5
    to: 'playing'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    service: scene.turn_on
    entity_id: scene.basement_dim

# updater notification
- alias: 'Update Available Notifications'
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    service: notify.notify
    data:
      message: 'Update for Home Assistant is available.'

# alternate updater notification
- alias: 'alternate updater notifier'
  trigger:
    platform: template
    value_template: "{% if states.sensor.installed_version != states.sensor.current_ha_version %}true{% endif %}"
  action:
    service: notify.notify
    data:
      message: 'Update for Home Assistant is available.'

#Turn on living room reading lamp in evening
- alias: 'turn on living room reading lamp on in evening'
  trigger:
    platform: sun
    event: sunset
    offset: "-01:00:00"
  action:
    service: switch.turn_on
    entity_id: switch.living_room_reading_lamp_switch_2_0

#Turn off living room reading lamp at bedtime
- alias: 'turn off living room reading lamp at bedtime'
  trigger:
    platform: time
    after: '23:00:00'
  action:
    service: switch.turn_off
    entity_id: switch.living_room_reading_lamp_switch_2_0

- alias: 'zwave soft reset at 2:30am'
  trigger:
    platform: time
    after: '2:30:00'
  action:
    service: script.zwave_reset

- alias: 'zwave heal at 2:33am'
  trigger:
    platform: time
    after: '2:33:00'
  action:
    service: script.zwave_healer

- alias: 'motion detected'
#  initial_state: False
  trigger:
    platform: mqtt
    topic: 'homeassistant/motion'
  condition:
    - condition: state
      entity_id: device_tracker.jays7_galaxy_s7
      state: 'not_home'
  action:
    service: notify.notify
    data_template:
      message: "motion detected: {{ trigger.payload_json['camera'] ~ ' ' ~ trigger.payload_json['time'] ~ ' ' ~ trigger.payload_json['date'] }}"

- alias: 'motion detection automation on'
  trigger:
    platform: state
    entity_id: device_tracker.jays7_galaxy_s7
#    from: 'home'
    to: 'not_home'
    for:
      minutes: 5
  action:
    service: shell_command.motion_auto_on

- alias: 'motion detection automation off'
  trigger:
    - platform: state
      entity_id: device_tracker.jays7_galaxy_s7
      from: 'not_home'
      to: 'home'
      for:
        minutes: 2
    - platform: state
      entity_id: device_tracker.jays7_galaxy_s7
      to: 'den'
      for:
        minutes: 2
  action:
    service: shell_command.motion_auto_off

- alias: 'turn on kitchen lights if too dark and motion'
  trigger:
    platform: numeric_state
    entity_id: sensor.kitchen_burglar_11_10
    above: '2'
  condition:
    - condition: numeric_state
      entity_id: sensor.kitchen_luminance_11_3
      below: '15'
  action:
    service: switch.turn_on
    entity_id: switch.kitchen_switch_4_0  

- alias: 'turn on basement lights if too dark and motion'
  trigger:
    platform: numeric_state
    entity_id: sensor.basement_burglar_22_10
    above: '3'
  condition:
    - condition: numeric_state
      entity_id: sensor.basement_luminance_22_3
      below: '25'
  action:
    service: script.basement_lights_on

- alias: 'turn on entryway light if too dark and motion'
  trigger:
    platform: numeric_state
    entity_id: sensor.entry_burglar_24_10
    above: '2'
  condition:
    - condition: numeric_state
      entity_id: sensor.entry_luminance_24_3
      below: '25'
  action:
    service: scene.turn_on
    entity_id: scene.entry_hall_on

- alias: 'track sensor state of Jay Room Locator'
  trigger:
    platform: mqtt
    topic: owntracks/jays7/galaxy s7/event
  condition:
    condition: template
    value_template: "{{ trigger.payload_json['desc'] == '-den' }}"
  action:
    service_template: "input_boolean.turn_{{ 'on' if trigger.payload_json['event'] == 'enter' else 'off' }}"
    data:
      entity_id: input_boolean.jay_phone_den
    
- alias: 'turn on den lights when entering den'
  trigger:
    - platform: state
      entity_id: sensor.jay_room_locator
      state: 'enter den'
      for:
        seconds: 3
    - platform: state
      entity_id: device_tracker.jays7_galaxy_s7
      state: 'den'
      for:
        seconds: 3
  condition:
    condition: state
    entity_id: input_boolean.jay_phone_den
    state: 'on'
  action:
    service: light.turn_on
    entity_id:
      - light.den
      - light.den_window
      - light.desk_drawer_level_14_0
      - light.tiffany_level_12_0
      - light.den_corner

- alias: 'turn off den lights when leaving den'
  trigger:
    - platform: state
      entity_id: device_tracker.jays7_galaxy_s7
      state: 'not_home'
      for:
        minutes: 2
    - platform: state
      entity_id: device_tracker.jays7_galaxy_s7
      state: 'home'
      for:
        minutes: 2
    - platform: state
      entity_id: device_tracker.jays7_galaxy_s7
      state: 'master_bedroom'
      for:
        minutes: 2
  condition:
    condition: state
    entity_id: input_boolean.jay_phone_den
    state: 'off'
  action:
    service: light.turn_off                                                                
    entity_id:
      - light.den
      - light.den_window
      - light.desk_drawer_level_14_0
      - light.tiffany_level_12_0
      - light.den_corner

- alias: 'Lily Away'
  condition:
    condition: state
    entity_id: input_boolean.lily_home
    state: 'on'
  trigger:
    - platform: state
      entity_id: device_tracker.203cae4707ce
      to: 'not_home'
    - platform: state
      entity_id: device_tracker.020fb54707ce
      to: 'not_home'
  action:
     service: input_boolean.turn_off
     data:
       entity_id: input_boolean.lily_home

- alias: 'Lily Home'
  condition:
    condition: state
    entity_id: input_boolean.lily_home
    state: 'off'
  trigger:
    - platform: state
      entity_id: device_tracker.203cae4707ce
      to: 'home'
    - platform: state
      entity_id: device_tracker.020fb54707ce
      to: 'home'
  action:
     service: input_boolean.turn_on
     data:
       entity_id: input_boolean.lily_home

- alias: 'Madeline Away'
  condition:
    condition: state
    entity_id: input_boolean.maddie_home
    state: 'on'
  trigger:
    - platform: state
      entity_id: device_tracker.020fb572f640
      to: 'not_home'
    - platform: state
      entity_id: device_tracker.bc9fef72f640
      to: 'not_home'
  action:
     service: input_boolean.turn_off
     entity_id: input_boolean.maddie_home

- alias: 'Madeline Home'
  condition:
    condition: state
    entity_id: input_boolean.maddie_home
    state: 'off'
  trigger:
    - platform: state
      entity_id: device_tracker.020fb572f640
      to: 'home'
    - platform: state
      entity_id: device_tracker.bc9fef72f640
      to: 'home'
  action:
     service: input_boolean.turn_on
     entity_id: input_boolean.maddie_home

- alias: 'turn off den detection automation'
  trigger:
    platform: time
    after: '01:59:00'
  action:
    service: shell_command.den_detect_off

- alias: 'turn on den detection automation'
  trigger:
    platform: time
    after: '06:00:00'
  action:
    service: shell_command.den_detect_on

#turn off basement lights if jay is not downstairs
- alias: 'turn off basement lights based on presence'
  trigger:
    - platform: state
      entity_id: device_tracker.jays7_galaxy_s7
      to: 'den'
    - platform: state
      entity_id: device_tracker.jays7_galaxy_s7
      to: 'master_bedroom'
    - platform: state
      entity_id: device_tracker.jays7_galaxy_s7
      to: 'not_home'
  action:
    service: homeassistant.turn_off
    entity_id:  
      - light.basement_3way_dimmer_level_25_0
      - light.basement_cabinet
      - light.basement_wall
      - switch.basement_stairs_switch_3_0
      - light.lightstrip

#turn off kitchen lights at night on presence state
- alias: 'turn off kitchen lights based on presence at night'
  trigger:
    platform: state
    entity_id: sensor.kitchen_burglar_11_10
    to: '0'
  condition:
    condition: time
    after: '21:30:00'
    before: '07:00:00'
  action:
    service: homeassistant.turn_off
    entity_id: switch.kitchen_switch_4_0

#turn off entryway lights when no presence detected
- alias: 'turn off entryway lights based when no presence detected'
  trigger:
    platform: state
    entity_id: sensor.entry_burglar_24_10
    to: '0'
  action:
    service: light.turn_off
    entity_id: light.entry_hall
