
homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  elevation: 1944
  # C for Celsius, F for Fahrenheit
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Denver
  customize: !include customize.yaml

# View all events in a logbook
logbook:


# Checks for available updates
updater:

# Show links to resources in log and frontend
#introduction:

# Discover some devices automatically
discovery:
  ignore:
    - roku
    - samsung_tv

zoneminder:
  host: 192.168.1.165
  path: /zm/
  path_zms: /zm/cgi-bin/nph-zms
  username: !secret blue
  password: !secret bluep

http:
  api_password: !secret http_pass
#  ssl_certificate: !secret ha_ssl_cert
#  ssl_key: !secret ha_ssl_key
#  base_url: !secret ha_base_url
  trusted_networks:
    - 192.168.1.0/24

tts:
  - platform: google
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300

hue:
  bridges:
    - host: 192.168.1.137

media_player:
  - platform: sonos
  - platform: openhome

wink:
  email: !secret wink_email
  password: !secret wink_pass
  client_id: !secret wink_client_id
  client_secret: !secret wink_client_secret

ring:
  username: !secret ring
  password: !secret ringp

zwave:
  usb_path: /dev/ttyACM0
  config_path: /srv/jhass/src/python-openzwave/openzwave/config
  autoheal: False
  new_entity_ids: true

notify:
  platform: pushbullet
  api_key: !secret notify_api

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

cover:
  - platform: myq
    name: Garage Door
    username: !secret myq_user
    password: !secret myq_pass
    type: liftmaster

shell_command:
  motion_auto_off: /usr/bin/python3 /home/jay/auto-motion.py
  motion_auto_on: /usr/bin/python3 /home/jay/auto-motion-on.py
  den_detect_on: /usr/bin/python3 /home/jay/den-detection-on.py
  den_detect_off: /usr/bin/python3 /home/jay/den-detection-off.py
  reload_ffmpeg: /usr/bin/python3 /home/jay/reload-ffmpeg.py

mqtt:
  broker: !secret mqtt_broker
  port: 1883
  client_id: jay-ha
  keepalive: 60
  username: !secret mqtt_user
  password: !secret mqtt_pass

#mqtt_statestream:
#  base_topic: homeassistant
#  publish_attributes: true
#  publish_timestamps: true

device_tracker:
  - platform: owntracks
    consider_home: 180
#  - platform: mqtt
#    devices:
#      jay_note_4: /location/jay
#      jayn5_nexus_5x: /location/jayn5
#      jays7_galaxy_s7: /location/jays7
  - platform: asuswrt
    consider_home: 180
    host: 192.168.1.1
    username: !secret ngear
    ssh_key: !secret asuswrt_ssh_key
    port: 22
    new_device_defaults:
      track_new_devices: false
      hide_if_away: false
  - platform: nmap_tracker
    consider_home: 180
    hosts:
      - 192.168.1.147
      - 192.168.1.154
      - 192.168.1.146
      - 192.168.1.159
      - 192.168.1.120
    home_interval: 15
    scan_options: " --privileged -p 62078 -sS "
  - platform: tile
    consider_home: 600
    username: !secret tile_user
    password: !secret tile_pw


input_select:
  jay_room_tracker:
    name: "Jay is in room"
    options:
      - den
      - master
      - livingroom
      - kitchen
      - basement
      - gym
    icon: mdi:home

emulated_hue:
  expose_by_default: false

group: !include groups.yaml

automation: !include_dir_merge_list automation/

scene: !include scenes.yaml

script: !include scripts.yaml

camera: !include_dir_merge_list camera/

zone: !include_dir_merge_list zone/

sensor: !include_dir_merge_list sensors/

input_boolean: !include_dir_merge_named input_booleans/

logger:
  default: error
  logs:
    homeassistant.components.camera: warning

ffmpeg:
  ffmpeg_bin: /usr/local/bin/ffmpeg

binary_sensor:
  - platform: nest
    monitored_conditions:
      - 'online'
      - 'is_using_emergency_heat'
  - platform: ffmpeg_noise
    name: basement_sound
    input: -rtsp_transport tcp -i rtsp://192.168.1.214:554/ch0_0.h264
    peak: -25
    duration: 1
  - platform: ring

timer:
  porch:
    duration: '00:05:00'

# Allows you to issue voice commands from the frontend
conversation:

# Enables the frontend
frontend:

# Enables support for tracking state changes over time.
history:

# Track the sun
sun:

map:

recorder:
  db_url: !secret recorder_db_url
  purge_interval: 2
  purge_keep_days: 14
