#- platform: ffmpeg
#  name: Yi LR
#  input: -rtsp_transport tcp -i rtsp://192.168.1.213:554/ch0_0.h264
#- platform: ffmpeg
#  name: Yi Garage
#  input: -rtsp_transport tcp -i rtsp://192.168.1.215:554/ch0_0.h264
#- platform: ffmpeg
#  name: Yi Basement
#  input: -rtsp_transport tcp -i rtsp://192.168.1.214:554/ch0_0.h264
#- platform: mjpeg
#  mjpeg_url: http://192.168.1.166:89/mjpg/YiLR
#  name: livingroom
#  username: !secret blue
#  password: !secret bluep
#  authentication: basic
#- platform: mjpeg
#  mjpeg_url: http://192.168.1.166:89/mjpg/YiB
#  name: basement
#  username: !secret blue
#  password: !secret bluep
#  authentication: basic
#- platform: mjpeg
#  mjpeg_url: http://192.168.1.166:89/mjpg/YiG
#  name: garage
#  username: !secret blue
#  password: !secret bluep
#  authentication: basic
- platform: zoneminder
- platform: mjpeg
#  mjpeg_url: http://192.168.1.160:32772/zm/cgi-bin/nph-zms?mode=jpeg&scale=100&maxfps=5&buffer=1000&monitor=2&user=jay-ha&connkey=757229&rand=1488983459
  mjpeg_url: http://192.168.2.100/zm/cgi-bin/nph-zms?mode=jpeg&scale=100&maxfps=5&buffer=1000&monitor=2&user=admin&connkey=848243&rand=1488857225
  name: garage
  username: !secret mqtt_user
  password: !secret mqtt_pass
  authentication: basic
- platform: mjpeg
#  mjpeg_url: http://192.168.1.160:32772/zm/cgi-bin/nph-zms?mode=jpeg&scale=100&maxfps=5&buffer=1000&monitor=3&user=jay-ha&connkey=696940&rand=1488983413
  mjpeg_url: http://192.168.2.100/zm/cgi-bin/nph-zms?mode=jpeg&scale=100&maxfps=5&buffer=1000&monitor=3&user=admin&connkey=601718&rand=1488857266
  name: basement
  username: !secret mqtt_user
  password: !secret mqtt_pass
  authentication: basic
- platform: mjpeg
  mjpeg_url: http://192.168.2.100/zm/cgi-bin/nph-zms?mode=jpeg&scale=100&maxfps=5&buffer=1000&monitor=4&user=admin&connkey=430352&rand=1489346525
  username: !secret mqtt_user
  password: !secret mqtt_pass
  authentication: basic
- platform: mjpeg
  mjpeg_url: http://192.168.2.100/zm/cgi-bin/nph-zms?mode=jpeg&scale=100&maxfps=5&buffer=1000&monitor=5&user=admin&connkey=323283&rand=1489346711
  name: master
  username: !secret mqtt_user
  password: !secret mqtt_pass
  authentication: basic
