- platform: ffmpeg
  name: Yi LR
  input: -rtsp_transport tcp -i rtsp://192.168.1.213:554/ch0_0.h264
- platform: ffmpeg
  name: Yi Garage
  input: -rtsp_transport tcp -i rtsp://192.168.1.215:554/ch0_0.h264
- platform: ffmpeg
  name: Yi Basement
  input: -rtsp_transport tcp -i rtsp://192.168.1.214:554/ch0_0.h264

