- platform: zoneminder
- platform: ring
- platform: generic
  name: Grafana_Temps
  still_image_url: 'http://192.168.1.107:3000/render/d-solo/ckTBIaxmk/home-stats?refresh=15m&orgId=1&panelId=2&width=1000&height=500&tz=America%2FDenver'
  username: !secret grafana_user
  password: !secret grafana_pass
- platform: generic
  name: Grafana_Current_Outdoor_Temp
  still_image_url: 'http://192.168.1.107:3000/render/d-solo/ckTBIaxmk/home-stats?refresh=15m&orgId=1&panelId=6&width=1000&height=500&tz=America%2FDenver'
  username: !secret grafana_user
  password: !secret grafana_pass
- platform: generic
  name: Grafana_Current_Indoor_Temp
  still_image_url: 'http://192.168.1.107:3000/render/d-solo/ckTBIaxmk/home-stats?refresh=15m&orgId=1&panelId=4&width=1000&height=500&tz=America%2FDenver'
  username: !secret grafana_user
  password: !secret grafana_pass
