#Turn on basement corner light in late pm
- alias: 'basement corner light in late pm'
  trigger:
    platform: time
    after: '15:00:00'
  action:
    service: light.turn_on
    entity_id:
      - light.basement

#Turn on basement stairs light in late pm
- alias: 'turn on basement stairs light in late pm'
  trigger:
    platform: sun
    event: sunset
    offset: "-02:00:00"
  action:
    service: switch.turn_on
    entity_id: switch.basement_stairs_switch_3_0

#Turn off basement corner light at 12:45am
- alias: 'basement corner light off at 12:45am'
  trigger:
    platform: time
    after: '00:45:00'
  action:
    service: light.turn_off
    entity_id:
      - light.basement

#Turn off basement lights in late pm
- alias: 'turn off basement lights in late pm'
  trigger:
    platform: time
    after: "00:00:00"
  action:
    service: homeassistant.turn_off
    entity_id:
      - switch.basement_stairs_switch_3_0
      - light.basement_3way_dimmer_level_25_0
      - light.basement_wall
      - light.basement_cabinet

- alias: 'turn on basement lights if too dark and motion'
  trigger:
    platform: numeric_state
    entity_id: sensor.basement_burglar_22_10
    above: '3'
  condition:
    - condition: numeric_state
      entity_id: sensor.basement_luminance_22_3
      below: '25'
  action:
    service: script.basement_lights_on

#turn off basement lights if jay is not downstairs and kids not home
- alias: 'turn off basement lights based on presence'
  trigger:
    platform: state
    entity_id: sensor.jay_in_which_room
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.lily_home
        state: 'off'
      - condition: state
        entity_id: input_boolean.maddie_home
        state: 'off'
      - condition: state
        entity_id: sensor.basement_luminance_22_3
        state: '0'
      - condition: template
        value_template: "{{ 'basement' not in trigger.to_state.state }}"
  action:
    service: homeassistant.turn_off
    entity_id: 
      - light.basement_3way_dimmer_level_25_0
      - light.basement_cabinet
      - light.basement_wall
      - switch.basement_stairs_switch_3_0
      - light.lightstrip

#turn off basement lights if no motion and no one downstairs
- alias: 'turn off basement lights based on motion & no presence'
  trigger:
    platform: state
    entity_id: sensor.basement_burglar_22_10
    to: '0'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.lily_home
        state: 'off'
      - condition: state
        entity_id: input_boolean.maddie_home
        state: 'off'
      - condition: template
        value_template: "{{ 'basement' not in states.sensor.jay_in_which_room.state }}"
  action:
    service: homeassistant.turn_off
    entity_id:
      - light.basement_3way_dimmer_level_25_0
      - light.basement_cabinet
      - light.basement_wall
      - switch.basement_stairs_switch_3_0
      - light.lightstrip

