#when basement nuc player pauses
- alias: "Media player paused"
  trigger:
    platform: state
    entity_id: media_player.nuci5_3
    from: 'playing'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    service: scene.turn_on
    entity_id: scene.basement_normal

#when basement nuc player starts playing
- alias: "Media player plays"
  trigger:
    platform: state
    entity_id: media_player.nuci5_3
    to: 'playing'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    service: scene.turn_on
    entity_id: scene.basement_dim
