#Turn on den light in morning during the week
- alias: 'den light in morning during the week'
  trigger:
    platform: time
    at: '07:00:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    service: light.turn_on
    entity_id:
      - light.den
      - light.den_window
      - light.desk_drawer_level
      - light.tiffany_level

#Turn off den lights during the week
- alias: 'den lights off at 10pm during the week'
  trigger:
    platform: time
    at: '22:00:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    service: light.turn_off
    entity_id:
      - light.den
      - light.den_window
      - light.desk_drawer_level
      - light.tiffany_level

#turn on den lights when entering den
- alias: 'turn on den lights when entering den'
  trigger:
#    - platform: state
#      entity_id: sensor.jay_in_which_room
#      to: 'enter den'
#      for:
#        seconds: 3
#    - platform: state
#      entity_id: device_tracker.jays7_galaxy_s7
#      to: 'den'
#      for:
#        seconds: 3
#    - platform: state
#      entity_id: input_boolean.jay_phone_den
#      to: 'on'
    - platform: numeric_state
      entity_id: sensor.den_burglar
      above: '2'
  condition:
    condition: time
    after: '06:00:00'
    before: '01:00:00'
  action:
    service: light.turn_on
    entity_id:
      - light.den
      - light.den_window
      - light.desk_drawer_level
      - light.tiffany_level
      - light.den_corner

#turn off den lights when leaving den
- alias: 'turn off den lights when leaving den'
  trigger:
    - platform: state
      entity_id: sensor.den_burglar
      to: '0'
      for:
        minutes: 3
    - platform: state
      entity_id: sensor.jay_wifi_locator
      to: 'master bedroom'
      for:
        minutes: 3
    - platform: state
      entity_id: sensor.jay_wifi_locator
      to: 'basement'
      for:
        minutes: 3
    - platform: state
      entity_id: sensor.jay_wifi_locator
      to: 'livingroom'
      for:
        minutes: 9
    - platform: state
      entity_id: sensor.jay_wifi_locator
      to: 'kitchen'
      for:
        minutes: 3
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ 'den' not in states('sensor.jay_wifi_locator') }}"
      - condition: template
        value_template: "{{ '8' not in states('sensor.den_burglar') }}"
#      - condition: state
#        entity_id: group.jay
#        to: 'home'
  action:
    service: light.turn_off
    entity_id:
      - light.den
      - light.den_window
      - light.desk_drawer_level
      - light.tiffany_level
      - light.den_corner

#turn off den lights when not home
- alias: 'turn off den lights when leaving den when not home'
  trigger:
    - platform: state
      entity_id: group.jay
      to: 'not_home'
      for:
        minutes: 5
  action:
    service: light.turn_off
    entity_id:
      - light.den
      - light.den_window
      - light.desk_drawer_level
      - light.tiffany_level
      - light.den_corner

#- alias: 'turn off den detection automation'
#  initial: off
#  trigger:
#    platform: time
#    at: '01:59:00'
#  action:
#    service: shell_command.den_detect_off

# alias: 'turn on den detection automation'
#  initial: off
#  trigger:
#    platform: time
#    at: '06:00:00'
#  action:
#    service: shell_command.den_detect_on
