- alias: 'turn off front bedroom lights @ 8am'
  trigger:
    platform: time
    at: '8:00:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    service: light.turn_off
    entity_id:
      - light.front_bedroom
      - light.dining_room_level
