##############################
#                            #
#  MULTIROOM LIGHT CONTROLS  #
#                            #
##############################

#Turn off lights at midnight
- alias: 'lights off at midnight'
  trigger:
    platform: time
    at: '23:59:00'
  action:
    service: light.turn_off
    entity_id:
      - light.master
      - light.master_corner
      - light.living_room_c_table
      - light.living_room_corner
      - light.den_corner

#Turn off any lights in early morning
- alias: 'any lights off in early am'
  trigger:
    platform: time
    at: '02:30:00'
  action:
    service: homeassistant.turn_off
    entity_id:
      - light.entry_hall
      - light.front_hall_table
      - light.office
      - light.lightstrip
      - switch.kitchen_switch
      - light.living_room

##############################
#                            #
#      CAMERA AUTOMATION     #
#                            #
##############################

#Turn on living room camera switch based on battery levels
- alias: 'lr camera switch on'
  trigger:
    platform: template
    value_template: "{% if states ('sensor.note_4_battery') | int < 60 %}true{% endif %}"
  action:
    service: switch.turn_on
    entity_id: switch.living_room_camera_power

#Turn off living room camera switch based on battery levels
- alias: 'lr camera switch off'
  trigger:
    platform: template
    value_template: "{% if states ('sensor.note_4_battery') | int > 95 %}true{% endif %}"
  action:
    service: switch.turn_off
    entity_id: switch.living_room_camera_power

#Turn on master bedroom phone power switch based on battery levels
- alias: 'master phone pwr switch on'
  trigger:
    platform: template
    value_template: "{% if states ('sensor.nexus_5x_battery') | int < 65 %}true{% endif %}"
  action:
    service: switch.turn_on
    entity_id: switch.bedroom_phone_power

#Turn off master bedroom phone power switch based on battery levels
- alias: 'master phone pwr switch off'
  trigger:
    platform: template
    value_template: "{% if states ('sensor.nexus_5x_battery') | int  > 90 %}true{% endif %}"
  action:
    service: switch.turn_off
    entity_id: switch.bedroom_phone_power

##############################
#                            #
#    UPDATER AUTOMATION      #
#                            #
##############################

# updater notification
- alias: 'Update Available Notifications'
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    service: notify.notify
    data:
      message: 'Update for Home Assistant is available.'

# alternate updater notification
- alias: 'alternate updater notifier'
  trigger:
    platform: template
    value_template: "{% if states.sensor.installed_version != states.sensor.current_ha_version %}true{% endif %}"
  action:
    service: notify.notify
    data:
      message: 'Update for Home Assistant is available.'

# Wink updater notification
- alias: 'wink update needed notifier'
  trigger:
    platform: template
    value_template: '{% if states.binary_sensor.gwink.attributes["update needed"] == true %}true{%else%}false{%endif%}'
  action:
    service: notify.notify
    data:
      message: 'Update for Wink is available.'

##############################
#                            #
#     NIGHTLY ZWAVE RESET    #
#                            #
##############################

- alias: 'zwave soft reset at 2:30am'
  trigger:
    platform: time
    at: '2:30:00'
  action:
    service: script.zwave_reset

- alias: 'zwave heal at 2:33am'
  trigger:
    platform: time
    at: '2:33:00'
  action:
    service: script.zwave_healer

##############################
#                            #
# MOTION DETECTION NOTIFIER  #
#                            #
##############################

- alias: 'motion detected'
#  initial_state: False
  trigger:
    platform: mqtt
    topic: 'homeassistant/motion/#'
  condition:
    - condition: state
      entity_id: group.family
      state: 'not_home'
  action:
    service: notify.notify
    data_template:
      message: "motion detected: {{ trigger.payload_json['camera'] ~ ' ' ~ trigger.payload_json['time'] ~ ' ' ~ trigger.payload_json['date'] }}"

##############################
#                            #
#      group visibility      #
#                            #
##############################

##############################
#                            #
#  MOTION AUTOMATION CONTROL #
#                            #
##############################

#- alias: 'motion detection automation on'
#  trigger:
#    platform: state
#    entity_id: device_tracker.jays7_galaxy_s7
#    from: 'home'
#    to: 'not_home'
#    for:
#      minutes: 5
#  action:
#    service: shell_command.motion_auto_on

#- alias: 'motion detection automation off'
#  trigger:
#    - platform: state
#      entity_id: device_tracker.jays7_galaxy_s7
#      from: 'not_home'
#      to: 'home'
#      for:
#        minutes: 2
#    - platform: state
#      entity_id: device_tracker.jays7_galaxy_s7
#      to: 'den'
#      for:
#        minutes: 2
#  action:
#    service: shell_command.motion_auto_off
